# Generated by Django 3.2.5 on 2021-07-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210720_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Sigla'),
        ),
    ]
