# Generated by Django 3.2.5 on 2021-07-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketing_price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotional_marketing_price',
            field=models.FloatField(default=0, verbose_name='Preço Promocional'),
        ),
    ]
